<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercices Routing</title>
        <link rel="stylesheet" href="assets/styles/style.css">
    </head>
    <body>
          <?php require "./templates/partials/_header.phtml"; ?>
        <?php  
        $template = routing(); 
        if($template==="about"){
            require "templates/partials/_about.phtml";
        }else if($template === "contact"){
            require "templates/partials/_contact.phtml";
        }else{
            require "templates/partials/_homepage.phtml";
        }
        ?>
             
       
        <?php require "./templates/partials/_footer.phtml"; ?>
       

    </body>
</html>